apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ai-k8s-basic
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend-k8s-basic-container
        image: machgo/dotnetonkubebackend:0.1
        ports:
        - containerPort: 80
        env:
        - name: TEST_ENV
          value: blubb
---
apiVersion: v1
kind: Service
metadata:
  name: ai-k8s-basic
spec:
  ports:
  - name: http-port
    port: 80
    targetPort: 80
  selector:
    app: backend
  type: LoadBalancer